name: CI/CD Pipeline

on:
  push:
    branches: [ "main","feature-branch" ]

# הרשאות נדרשות עבור ה-CD (העלאת האתר ל-GitHub Pages)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # ------------------------------------
  # חלק 1: CI (Continuous Integration)
  # ------------------------------------
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        # marketplace

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # ------------------------------------
  # חלק 2: CD (Continuous Deployment)
  # ------------------------------------
  deploy:
    needs: build-and-test # הרצה רק אם שלב ה-CI עבר בהצלחה!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # הנתיב של הקבצים שיועלו (index.html, js, css)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4